version: "3.5"

services:
    lumen:
        build:
            context: .
        ports:
            - "${APP_PORT:-8000}:8000"
        volumes:
            - .:/var/www/html
        command: /var/www/html/scripts/entry-point.sh
        networks:
            - microservice
networks:
    microservice:
        driver: bridge
volumes:
    mysql-data:
        driver: local
