version: "3.5"

services:
    lumen:
        build:
            context: .
            target: production
        ports:
            - "${APP_PORT:-8000}:8000"
        volumes:
            - .env:/var/www/html/.env
        networks:
            - microservice

networks:
    microservice:
        driver: bridge
