version: "3.5"

services:
    lumen:
        build: .
        ports:
            - "${APP_PORT:-8000}:8000"
        volumes:
            - .:/var/www/html
        command: /var/www/html/scripts/entry-point.sh
        networks:
            - microservice
        depends_on:
            - mysql
    mysql:
        image: mysql:8.0
        ports:
            - "${DB_PORT:-3306}:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        command: mysqld --init-file /data/application/init.sql
                        --default-authentication-plugin=mysql_native_password # required to be specified as of MySQL 8.0
        volumes:
            - ./database/init.sql:/data/application/init.sql
            - mysql-data:/var/lib/mysql:rw
        networks:
            - microservice
networks:
    microservice:
        driver: bridge
volumes:
    mysql-data:
        driver: local
