FORMAT: 1A

# Service Name

# Service Discovery [/api/v1/discovery]
Service discovery endpoints for identity and health checking.

## Get the service name and version [GET /api/v1/discovery]


+ Response 200 (application/json)
    + Body

            {
                "name": "example-service",
                "version": "Lumen (8.2.4) (Laravel Components ^8.0)"
            }