name: CI

on:
    push:
        branches: [main, staging]
    pull_request:
        branches: [main, staging]

jobs:
    build:
        runs-on: ubuntu-latest
        services:
            mysql:
                image: mysql:8.0
                ports:
                    - 3306:3306
                env:
                    MYSQL_ROOT_PASSWORD: password
                    MYSQL_USER: appuser
                    MYSQL_PASSWORD: secret
                    MYSQL_DATABASE: database
                volumes:
                    - /database/init.sql:/data/application/init.sql
                options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10
        steps:
            - name: Grant privileges
              run: mysql -uroot -ppassword < /data/application/init.sql

            - name: Checkout
              uses: actions/checkout@v2

            - name: Validate composer.json and composer.lock
              run: composer validate --strict

            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v2
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-

            - name: Install dependencies
              run: composer install --no-interaction --no-ansi --prefer-dist --no-progress

            - name: Acquire .env
              run: cp .env.ci .env

            - name: Run lint
              run: composer lint

            - name: Run test
              run: composer test
